name: Extraer Materiales

on:
  push:
    paths:
      - GM_2019_V1_1-303.pdf

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Instalar dependencias
      run: pip install -r requirements.txt

    - name: Ejecutar script
      run: python extract_materiales.py

    - name: Subir Excel generado
      uses: actions/upload-artifact@v3
      with:
        name: materiales
        path: materiales.xlsx
    - name: Commit y push Excel
    run: |
    git config --global user.name "github-actions"
    git config --global user.email "actions@github.com"
    git add docs/materiales.xlsx
    git commit -m "Actualizar Excel generado"
    git push
